services:
  auth-service:
    build:
      context: .
    container_name: auth
    image: auth-service
    environment:
      DB_HOST: db
    ports:
      - "1300:1300"
    networks:
      - backend

networks:
  backend:
    external: true